openapi: 3.0.1
info:
  title: TRQP Restful Binding
  version: 1.0.0
  description: |
    This specification defines a RESTful TRQP Binding.
    It includes endpoints for retrieving Trust Registry metadata,
    authorization data, verifying entity authorization status,
    and checking ecosystem recognition.
servers:
  - url: https://example-trust-registry.com
    description: Production server (example)

tags:
  - name: trqp-core
    description: TRQP Compliant Queries

paths:
  /recognition:
    post: 
      summary: Queries registry for recognition, by and ecosystem, of another ecosystem.
      tags:
        - trqp-core
      requestBody:  
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/TrqpRecognitionQuery'
      responses:
        200:
          description: Recognition query successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrqpRecognitionResponse'
        404:
          description: Entity not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        401:
          description: Unauthorized request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  /authorization:
    post: 
      summary: Queries registry for recognition, by and ecosystem, of another ecosystem.
      tags:
        - trqp-core
      requestBody:  
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/TrqpAuthorizationQuery'
      responses:
        200:
          description: Authorization query successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrqpAuthorizationResponse'
        404:
          description: Entity not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        401:
          description: Unauthorized request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
 
components:
  schemas:
    ProblemDetails:
      type: object
      description: |
        A Problem Details object as defined in [RFC 7807](https://datatracker.ietf.org/doc/html/rfc7807).
      properties:
        type:
          type: string
          format: uri
          description: A URI reference that identifies the problem type.
        title:
          type: string
          description: A short, human-readable summary of the problem.
        status:
          type: integer
          description: The HTTP status code (e.g., 404 for "Not Found").
        detail:
          type: string
          description: A human-readable explanation specific to this occurrence of the problem.
        instance:
          type: string
          format: uri
          description: A URI reference that identifies the specific occurrence of the problem.
      additionalProperties: true


    TrqpRecognitionQuery:
      type: object
      description: |
        A query request to a Trust Registry that supports TRQP 2.0. 
        Conforms with the schemas defined in TRQP 2.0. and matches the schema objects:
        - trqp_recognition_request.jsonschema
        Used by the following TRQP POST queries:
        - POST /recognition
      properties:
        entity_id:
          type: string
          description: |
            Unique identifier of the TRUST REGISTRY (identified by DID) that is the subject of the query. 
            This is the "other trust registry" in the "Does your ecosystem recognized this **other trust registry** as assertion_id?". 
        ecosystem_id:
          type: string
          description: |
            Unique identifier of the ECOSYSTEM (identified by DID) that is being queried. 
            This is the "your ecosystem" in the "Does **your ecosystem** recognize this other trust registry as assertion_id?".
        assertion_id:
          type: string
          description: |
            The assertion_id that is being tested against. 
            This is the `assertion_id` in the "Does your ecosystem recognize this other trust registry as **assertion_id**?".
        context:
          type: object
          properties:
            time:
              type: string
              format: date-time
              description: |
                RFC3339 timestamp indicating when recognition is checked. 
                Defaults to "now" on system being queried if omitted.
          additionalProperties:
            type: string
          description: |
            A flexible context object that can hold arbitrary key-value pairs. 
            - NOTE: `time` is codified as it is a standard context to be considered.
      required:
        - entity_id
        - ecosystem_id
        - assertion_id 

    TrqpAuthorizationQuery:
      type: object
      description: |
        A query request to a Trust Registry that supports TRQP 2.0. 
        Conforms with the schemas defined in TRQP 2.0. and matches the schema objects:
        - trqp_authorization_request.jsonschema
        Used by the following TRQP POST queries:
        - POST /authorization 
      properties:
        entity_id:
          type: string
          description: |
            Unique identifier of the TRUST REGISTRY (identified by DID) that is the subject of the query. 
            This is the 'EntityX` in the "Does **EntityX** have AuthorityY in EcosystemZ?". 
        ecosystem_id:
          type: string
          description: |
            Unique identifier of the ECOSYSTEM (identified by DID) that is being queried. 
            This is the "EcosystemZ" in the "Does EntityX have AuthorityY in **EcosystemZ**?". 
        assertion_id:
          type: string
          description: |
            The assertion_id that is being tested against. 
            This is the `AuthorityY` in the "Does EntityX have **AuthorityY** in **EcosystemZ**?". 
        context:
          type: object
          properties:
            time:
              type: string
              format: date-time
              description: |
                RFC3339 timestamp indicating when recognition is checked. 
                Defaults to "now" on system being queried if omitted.
          additionalProperties:
            type: string
          description: |
            A flexible context object that can hold arbitrary key-value pairs. 
            - NOTE: `time` is codified as it is a standard context to be considered.
      required:
        - entity_id
        - ecosystem_id
        - assertion_id 

    TrqpRecognitionResponse:
      type: object
      description: |
        A recognition response conforming to TRQP 2.0 specification and the
        trqp_recognition_response.jsonschema requirements.
      properties:
        entity_id:
          type: string
          description: The identifier of the subject of the recognition query.
        ecosystem_id:
          type: string
          description: The id of the Authority entity.
        assertion_id:
          type: string
          description: The identifier of the claim type being made against the entity_id.
        recognized:
          type: boolean
          description: True if the assertion has been verified, false otherwise.
        time_requested:
          type: string
          format: date-time
          description: The server time that was used in the query.
        time_evaluated:
          type: string
          format: date-time
          description: The server time that was used in the query.
        message:
          type: string
          description: Additional details attached to the response about the assertion.
        context:
          type: object
          description: The context object that was supplied for the query that was evaluated.
          properties:
            time:
              type: string
              format: date-time
              description: Time for query to use. If blank, uses current server time. RFC3339 required, using only Z (+00:00) offset.
          additionalProperties:
            type: string
      required:
        - entity_id
        - assertion_id
        - ecosystem_id
        - time_evaluated
        - recognized

    TrqpAuthorizationResponse:
      type: object
      description: |
        An authorization response conforming to TRQP 2.0 specification and the
        trqp_authorization_response.jsonschema requirements.
      properties:
        entity_id:
          type: string
          description: The identifier of the subject of the authorization.
        ecosystem_id:
          type: string
          description: The id of the Authority entity.
        assertion_id:
          type: string
          description: The identifier of the claim type being made against the entity_id.
        assertion_verified:
          type: boolean
          description: True if the assertion has been verified, false otherwise.
        time_requested:
          type: string
          format: date-time
          description: The server time that was requested (may be blank).
        time_evaluated:
          type: string
          format: date-time
          description: The server time that was used in the query.
        message:
          type: string
          description: Additional details attached to the response about the assertion.
        context:
          type: object
          description: The context object that was supplied for the query that was evaluated.
          properties:
            time:
              type: string
              format: date-time
              description: Time for query to use. If blank, uses current server time. RFC3339 required, using only Z (+00:00) offset.
          additionalProperties:
            type: string
      required:
        - entity_id
        - assertion_id
        - ecosystem_id
        - time_evaluated
        - assertion_verified
